laser_filters:
  ros__parameters:
    scan_filter_chain:
      - name: range_filter
        type: laser_filters/LaserScanRangeFilter
        params:
          use_message_range_limits: false
          min_range: 0.1
          max_range: 12.0
      - name: intensity_filter
        type: laser_filters/LaserScanIntensityFilter
        params:
          use_message_intensity_limits: false
          min_intensity: 0.0
          max_intensity: 1000.0
      - name: outlier_filter
        type: laser_filters/LaserScanOutlierFilter
        params:
          window_size: 5
          threshold: 0.5
      - name: shadow_filter
        type: laser_filters/LaserScanShadowFilter
        params:
          min_angle: 0.0
          max_angle: 0.0
          min_range: 0.1
          max_range: 12.0
