CLaserOdometry2DNode:
  ros__parameters:
    laser_scan_topic: /scan
    odom_topic: /odom_rf2o
    publish_tf: true
    base_frame_id: base_link
    odom_frame_id: odom
    laser_frame_id: laser_frame
    freq: 15.0
    verbose: false
    init_pose_from_topic: ""
    init_pose: [0.0, 0.0, 0.0]
    min_reading: 0.1
    max_reading: 12.0
    min_angle: -3.14159
    max_angle: 3.14159
    laser_pose_on_robot: [0.0, 0.0, 0.0]
    qos_overrides:
      /scan:
        subscription:
          reliability: best_effort
          durability: volatile
          history: keep_last
          depth: 50











